-- =====================================================================
-- hyprland.lua — Converted from hyprland.conf for Hyprland 0.55+
-- =====================================================================


-- #######################################################################################
-- AUTOGENERATED HYPRLAND CONFIG.
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.
-- #######################################################################################



-- This is an example Hyprland config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can split this configuration into multiple files
-- Create your files separately and then link them to this file like this:
-- source = ~/.config/hypr/myColors.conf




--###################
--### PERMISSIONS ###
--###################

-- See https://wiki.hypr.land/Configuring/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- ecosystem {
--   enforce_permissions = 1
-- }

-- permission = /usr/(bin|local/bin)/grim, screencopy, allow
-- permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
-- permission = /usr/(bin|local/bin)/hyprpm, plugin, allow


--------------------
---- MONITORS ----
--------------------

hl.monitor({
    output = "eDP-1",
    mode   = "1920x1200@60",
    position = "0x0",
    scale    = 1.5,
})

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

hl.env("GDK_SCALE",                        "1.5")
hl.env("GDK_DPI_SCALE",                    "1")
hl.env("QT_QPA_PLATFORMTHEME",             "qt6ct")
hl.env("QT_QPA_PLATFORM",                  "wayland;xcb")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("MOZ_ENABLE_WAYLAND",               "1")
hl.env("ELECTRON_OZONE_PLATFORM_HINT",     "wayland")
hl.env("GDK_BACKEND",                      "wayland,x11")
hl.env("GTK_THEME",                        "Adwaita:dark")
hl.env("XCURSOR_SIZE",                     "24")
hl.env("HYPRCURSOR_SIZE",                  "24")

---------------------
---- MY PROGRAMS ----
---------------------

local mainMod = "SUPER"
local terminal = "kitty"
local fileManager = "dolphin"
local menu = "wofi --show drun"

-------------------
---- AUTOSTART ----
-------------------

hl.on("hyprland.start", function()
    hl.exec_cmd("nm-applet")
    hl.exec_cmd("waybar")
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
    hl.exec_cmd("awww-daemon --no-cache")
    -- set wallpaper after daemon starts
    hl.exec_cmd("sleep 1 && awww img /home/abdul/Pictures/linux-customization-wallpaper-settings/minato-namikaze-magick-1920x1200.png --transition-type none")
end)

-----------------------
---- LOOK AND FEEL ----
-----------------------

hl.config({
    general = {
        gaps_in         = 5,
        gaps_out        = 15,
        border_size     = 2,
        col = {
            active_border   = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },
        resize_on_border = false,
        allow_tearing    = false,
        layout           = "dwindle",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,
        active_opacity   = 1.0,
        inactive_opacity = 1.0,
        shadow = {
            enabled = false,
        },
        blur = {
            enabled = false,
        },
    },

    animations = {
        enabled = true,
    },

    dwindle = {
        -- pseudotile     = true,
        preserve_split = true,
    },

    master = {
        new_status = "master",
    },

    misc = {
      -- vfr                    = true,
        force_default_wallpaper = 0,
        disable_hyprland_logo  = true,
        disable_splash_rendering = true,   -- ← add this
    },

    xwayland = {
        force_zero_scaling = true,
    },

    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",
        follow_mouse = 1,
        sensitivity  = 0,
        touchpad = {
            natural_scroll = false,
        },
    },
})

----------------------
---- ANIMATIONS ----
----------------------

hl.curve("wind",   { type = "bezier", points = { {0.05, 0.9}, {0.1, 1.05} } })
hl.curve("winIn",  { type = "bezier", points = { {0.1, 1.05}, {0.1, 1.05} } })
hl.curve("winOut", { type = "bezier", points = { {0.3, 0.0},  {0, 1}     } })
hl.curve("liner",  { type = "bezier", points = { {1, 1},      {1, 1}     } })

hl.animation({ leaf = "windows",      enabled = true, speed = 5, bezier = "wind",   style = "slide" })
hl.animation({ leaf = "windowsIn",    enabled = true, speed = 4, bezier = "winIn",  style = "slide" })
hl.animation({ leaf = "windowsOut",   enabled = true, speed = 3, bezier = "winOut", style = "slide" })
hl.animation({ leaf = "windowsMove",  enabled = true, speed = 4, bezier = "wind",   style = "slide" })
hl.animation({ leaf = "border",       enabled = true, speed = 1, bezier = "liner"  })
hl.animation({ leaf = "fade",         enabled = true, speed = 6, bezier = "default" })
hl.animation({ leaf = "workspaces",   enabled = true, speed = 4, bezier = "wind",   style = "slide" })

---------------------
---- GESTURES ----
---------------------

hl.config({
    gestures = {
        workspace_swipe_distance          = 200,
        workspace_swipe_invert            = false,
        workspace_swipe_min_speed_to_force = 10,
        workspace_swipe_cancel_ratio      = 0.2,
    },
})

-- 3-finger horizontal swipe → switch workspace
hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })

-- 4-finger swipe up → open wofi
hl.gesture({ fingers = 4, direction = "swipe", action = function()
    hl.exec_cmd("wofi --show drun")
end })


-- Apps
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + C", hl.dsp.window.close())
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + M", hl.dsp.exit())
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))

-- Super key alone (release) → toggle wofi
hl.bind(mainMod .. " + Super_L", hl.dsp.exec_cmd("pkill wofi || " .. menu), { release = true })

-- Layout
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))

-- Screen shader (software dim)
--hl.bind(mainMod .. " + F1", hl.dsp.exec_cmd("hyprctl keyword decoration:screen_shader ~/.config/hypr/shaders/dim.frag"))
--hl.bind(mainMod .. " + F2", hl.dsp.exec_cmd("hyprctl keyword decoration:screen_shader [[EMPTY]]"))

-- Focus
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left"  }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up"    }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down"  }))

-- Workspaces
for i = 1, 9 do
    hl.bind(mainMod .. " + " .. i,               hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. i,       hl.dsp.window.move({ workspace = i }))
end
hl.bind(mainMod .. " + 0",         hl.dsp.focus({ workspace = 10 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

-- Scratchpad
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through workspaces
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Screenshots
hl.bind("Print",       hl.dsp.exec_cmd("~/.config/hypr/screenshot.sh"))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd("~/.config/hypr/screenshot.sh region"))


-- Volume keys
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"),  { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),        { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),       { locked = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),     { locked = true })

-- Brightness keys
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })

-- Media keys
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),        { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"),  { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"),  { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),    { locked = true })

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

hl.window_rule({
    name               = "suppress-maximize-events",
    match              = { class = ".*" },
    suppress_event     = "maximize",
})

hl.window_rule({
    name           = "fix-xwayland-drags",
    match          = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },
    no_focus = true,
})

hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },
    move  = "20 monitor_h-120",
    float = true,
})