
# Optional: Add some padding so text isn't touching the window edges

#term xterm

#remember_window_size   no

#initial_window_width   1200
#initial_window_height  700

font_family JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 12.0

background_opacity 0.8

window_padding_width 10
